package galleryPkg;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Maria
 */
public class InsertFrame extends javax.swing.JFrame {

    /**
     * Creates new form InsertFrame
     */
    public InsertFrame() {
        initComponents();
        
        //populate comboboxes.
        connectQueries.FillArtistIdCbx(insertArtworkArtistIdCbx);
        connectQueries.FillOrderIdCbx(insertArtworkOrderIdCbx);
        connectQueries.FillArtistIdCbx(insertCustLikeArtistArtistIdCbx);
        connectQueries.FillCustomerIdCbx(insertOrderCustomerIdCbx);
        connectQueries.FillCustomerIdCbx(insertCustLikeArtistCustIdCbx);
        connectQueries.FillArtworkTitleCbx(insertArtworkClassGroupArtworkNameCbx);
        connectQueries.FillNameOfGroupCbx(insertArtworkClassGroupGroupNameCbx);
        connectQueries.FillArtworkTitleCbx(insertOrderTitleCbx);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mainMenuInsertFrameBtn = new javax.swing.JButton();
        disconnectInsertFrameBtn = new javax.swing.JButton();
        insertMsgLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        insertArtistNameTxt = new javax.swing.JTextField();
        insertArtistStyleTxt = new javax.swing.JTextField();
        insertArtistLocationTxt = new javax.swing.JTextField();
        insertArtistPhoneTxt = new javax.swing.JTextField();
        insertArtistSbtBtn = new javax.swing.JButton();
        insertArtistClrBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        insertCustomerNameTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        insertCustomerPhoneTxt = new javax.swing.JTextField();
        insertCustomerSbtBtn = new javax.swing.JButton();
        insertCustomerClrBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        insertArtworkGenreTxt = new javax.swing.JTextField();
        insertArtworkPriceTxt = new javax.swing.JTextField();
        insertArtworkCreationYearTxt = new javax.swing.JTextField();
        insertArtworkInsertionYearTxt = new javax.swing.JTextField();
        insertArtworkArtistIdCbx = new javax.swing.JComboBox();
        insertArtworkOrderIdCbx = new javax.swing.JComboBox();
        insertArtworkSbtBtn = new javax.swing.JButton();
        insertArtworkClrBtn = new javax.swing.JButton();
        insertArtworkTitleTxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        insertOrderOrderYearTxt = new javax.swing.JTextField();
        insertOrderCustomerIdCbx = new javax.swing.JComboBox();
        insertOrderSbtBtn = new javax.swing.JButton();
        insertOrderClrBtn = new javax.swing.JButton();
        insertOrderTitleCbx = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        insertGroupNameTxt = new javax.swing.JTextField();
        insertGroupSbtBtn = new javax.swing.JButton();
        insertGroupClrBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        insertCustLikeArtistCustIdCbx = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        insertCustLikeArtistArtistIdCbx = new javax.swing.JComboBox();
        insertCustLikeArtistSbtBtn = new javax.swing.JButton();
        insertCustLikeArtistClrBtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        insertArtworkClassGroupArtworkNameCbx = new javax.swing.JComboBox();
        insertArtworkClassGroupGroupNameCbx = new javax.swing.JComboBox();
        insertArtworkClassGroupArtworkSbtBtn = new javax.swing.JButton();
        insertArtworkClassGroupArtworkClrBtn = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Insert Records");

        mainMenuInsertFrameBtn.setText("MainMenu");
        mainMenuInsertFrameBtn.setPreferredSize(new java.awt.Dimension(85, 23));
        mainMenuInsertFrameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuInsertFrameBtnActionPerformed(evt);
            }
        });

        disconnectInsertFrameBtn.setText("Disconnect");
        disconnectInsertFrameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectInsertFrameBtnActionPerformed(evt);
            }
        });

        insertMsgLbl.setForeground(new java.awt.Color(255, 153, 51));
        insertMsgLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Insert Artist Record:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 102))); // NOI18N

        jLabel3.setText("Name: ");

        jLabel4.setText("Style: ");

        jLabel5.setText("Location (Country): ");

        jLabel6.setText("Phone Number:");

        insertArtistSbtBtn.setText("Submit");
        insertArtistSbtBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        insertArtistSbtBtn.setMinimumSize(new java.awt.Dimension(100, 23));
        insertArtistSbtBtn.setPreferredSize(new java.awt.Dimension(100, 23));
        insertArtistSbtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertArtistSbtBtnActionPerformed(evt);
            }
        });

        insertArtistClrBtn.setText("Clear");
        insertArtistClrBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        insertArtistClrBtn.setMinimumSize(new java.awt.Dimension(100, 23));
        insertArtistClrBtn.setPreferredSize(new java.awt.Dimension(100, 23));
        insertArtistClrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertArtistClrBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(insertArtistSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(insertArtistPhoneTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(insertArtistClrBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(insertArtistNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertArtistStyleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertArtistLocationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(insertArtistNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(insertArtistStyleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(insertArtistLocationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(insertArtistPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertArtistSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertArtistClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Insert Customer Record:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 102))); // NOI18N

        jLabel8.setText("Name: ");

        jLabel9.setText("Phone Number: ");

        insertCustomerSbtBtn.setText("Submit");
        insertCustomerSbtBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        insertCustomerSbtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertCustomerSbtBtnActionPerformed(evt);
            }
        });

        insertCustomerClrBtn.setText("Clear");
        insertCustomerClrBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        insertCustomerClrBtn.setMinimumSize(new java.awt.Dimension(100, 23));
        insertCustomerClrBtn.setPreferredSize(new java.awt.Dimension(100, 23));
        insertCustomerClrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertCustomerClrBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(insertCustomerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertCustomerPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(insertCustomerSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(insertCustomerClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(insertCustomerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(insertCustomerPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertCustomerSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertCustomerClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Insert Artwork Record:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 102))); // NOI18N

        jLabel12.setText("Title: ");

        jLabel13.setText("Genre: ");

        jLabel14.setText("Price: ");

        jLabel15.setText("Creation Year: ");

        jLabel16.setText("Insertion Year: ");

        jLabel17.setText("Artist ID: ");

        jLabel18.setText("Order ID: ");

        insertArtworkOrderIdCbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE" }));

        insertArtworkSbtBtn.setText("Submit");
        insertArtworkSbtBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        insertArtworkSbtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertArtworkSbtBtnActionPerformed(evt);
            }
        });

        insertArtworkClrBtn.setText("Clear");
        insertArtworkClrBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        insertArtworkClrBtn.setMinimumSize(new java.awt.Dimension(100, 23));
        insertArtworkClrBtn.setPreferredSize(new java.awt.Dimension(100, 23));
        insertArtworkClrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertArtworkClrBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(insertArtworkTitleTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertArtworkGenreTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertArtworkPriceTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertArtworkCreationYearTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertArtworkInsertionYearTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertArtworkArtistIdCbx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertArtworkOrderIdCbx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(insertArtworkSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(insertArtworkClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(insertArtworkTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(insertArtworkGenreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(insertArtworkPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(insertArtworkCreationYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(insertArtworkInsertionYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(insertArtworkArtistIdCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(insertArtworkOrderIdCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertArtworkSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertArtworkClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Insert Order Record:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 102))); // NOI18N

        jLabel21.setText("Title ordered artwork: ");

        jLabel22.setText("Order Year: ");

        jLabel23.setText("Customer ID: ");

        insertOrderSbtBtn.setText("Submit");
        insertOrderSbtBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        insertOrderSbtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertOrderSbtBtnActionPerformed(evt);
            }
        });

        insertOrderClrBtn.setText("Clear");
        insertOrderClrBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        insertOrderClrBtn.setMinimumSize(new java.awt.Dimension(100, 23));
        insertOrderClrBtn.setPreferredSize(new java.awt.Dimension(100, 23));
        insertOrderClrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertOrderClrBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(insertOrderSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(insertOrderOrderYearTxt)
                    .addComponent(insertOrderCustomerIdCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertOrderClrBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertOrderTitleCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(insertOrderTitleCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(insertOrderOrderYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(insertOrderCustomerIdCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertOrderSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertOrderClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Insert Group Record:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 102))); // NOI18N

        jLabel20.setText("Name of Group: ");

        insertGroupSbtBtn.setText("Submit");
        insertGroupSbtBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        insertGroupSbtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertGroupSbtBtnActionPerformed(evt);
            }
        });

        insertGroupClrBtn.setText("Clear");
        insertGroupClrBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        insertGroupClrBtn.setMinimumSize(new java.awt.Dimension(100, 23));
        insertGroupClrBtn.setPreferredSize(new java.awt.Dimension(100, 23));
        insertGroupClrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertGroupClrBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertGroupSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insertGroupNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertGroupClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(insertGroupNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertGroupSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertGroupClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Likes Artist Record: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 102))); // NOI18N

        jLabel25.setText("Customer ID: ");

        jLabel26.setText("Artist ID: ");

        insertCustLikeArtistSbtBtn.setText("Submit");
        insertCustLikeArtistSbtBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        insertCustLikeArtistSbtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertCustLikeArtistSbtBtnActionPerformed(evt);
            }
        });

        insertCustLikeArtistClrBtn.setText("Clear");
        insertCustLikeArtistClrBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        insertCustLikeArtistClrBtn.setMinimumSize(new java.awt.Dimension(100, 23));
        insertCustLikeArtistClrBtn.setPreferredSize(new java.awt.Dimension(100, 23));
        insertCustLikeArtistClrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertCustLikeArtistClrBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(insertCustLikeArtistCustIdCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertCustLikeArtistArtistIdCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(insertCustLikeArtistSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(insertCustLikeArtistClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(insertCustLikeArtistCustIdCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(insertCustLikeArtistArtistIdCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertCustLikeArtistSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertCustLikeArtistClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Artwork Classified to Group Record:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 102))); // NOI18N

        jLabel29.setText("Name of Group: ");

        insertArtworkClassGroupArtworkSbtBtn.setText("Submit");
        insertArtworkClassGroupArtworkSbtBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        insertArtworkClassGroupArtworkSbtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertArtworkClassGroupArtworkSbtBtnActionPerformed(evt);
            }
        });

        insertArtworkClassGroupArtworkClrBtn.setText("Clear");
        insertArtworkClassGroupArtworkClrBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        insertArtworkClassGroupArtworkClrBtn.setMinimumSize(new java.awt.Dimension(100, 23));
        insertArtworkClassGroupArtworkClrBtn.setPreferredSize(new java.awt.Dimension(100, 23));

        jLabel28.setText("Artwork Name: ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(insertArtworkClassGroupArtworkSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insertArtworkClassGroupArtworkNameCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertArtworkClassGroupGroupNameCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertArtworkClassGroupArtworkClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(insertArtworkClassGroupArtworkNameCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(insertArtworkClassGroupGroupNameCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertArtworkClassGroupArtworkSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertArtworkClassGroupArtworkClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(mainMenuInsertFrameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(disconnectInsertFrameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(insertMsgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mainMenuInsertFrameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(disconnectInsertFrameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(insertMsgLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuInsertFrameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuInsertFrameBtnActionPerformed
        MainFrame mainFrame = new MainFrame();
        mainFrame.setVisible(true);
        InsertFrame.this.setVisible(false);
        InsertFrame.this.dispose();
    }//GEN-LAST:event_mainMenuInsertFrameBtnActionPerformed

    private void disconnectInsertFrameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectInsertFrameBtnActionPerformed
        LoginFrame loginFrame = new LoginFrame();
            loginFrame.setVisible(true);
            InsertFrame.this.setVisible(false);
            connectQueries.disConnectDb();
            InsertFrame.this.dispose();
    }//GEN-LAST:event_disconnectInsertFrameBtnActionPerformed

    
    // INSERT ARTIST SUBMIT BUTTON
    private void insertArtistSbtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertArtistSbtBtnActionPerformed
        String artistName = insertArtistNameTxt.getText();
        String artistStyle = insertArtistStyleTxt.getText();
        String artistLocation = insertArtistLocationTxt.getText();
        int artistPhone = Integer.parseInt(insertArtistPhoneTxt.getText());
        
        
        if(connectQueries.insertArtistInsertFrame(artistName, artistStyle, artistLocation, artistPhone)){
            insertMsgLbl.setText("Artist Record Inserted Successfully.");
        }else{
            insertMsgLbl.setText("Artist Record Insertion Failed.");
        }
    }//GEN-LAST:event_insertArtistSbtBtnActionPerformed

    
    // INSERT ARTIST CLEAR BUTTON
    private void insertArtistClrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertArtistClrBtnActionPerformed
        insertArtistNameTxt.setText("");
        insertArtistStyleTxt.setText("");
        insertArtistLocationTxt.setText("");
        insertArtistPhoneTxt.setText("");
        
        insertMsgLbl.setText("");
    }//GEN-LAST:event_insertArtistClrBtnActionPerformed

    // INSERT CUSTOMER SUBMIT BUTTON
    private void insertCustomerSbtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertCustomerSbtBtnActionPerformed
        String customerName = insertCustomerNameTxt.getText();
        int customerPhone = Integer.parseInt(insertCustomerPhoneTxt.getText());
        
        if(connectQueries.insertCustomerInsertFrame(customerName, customerPhone)){
            insertMsgLbl.setText("Customer Record Inserted Successfully.");
        }else{
            insertMsgLbl.setText("Artist Record Insertion Failed.");
        }
    }//GEN-LAST:event_insertCustomerSbtBtnActionPerformed

    // INSERT CUSTOMER CLEAR BUTTON
    private void insertCustomerClrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertCustomerClrBtnActionPerformed
        insertCustomerNameTxt.setText("");
        insertCustomerPhoneTxt.setText("");
        insertMsgLbl.setText("");
    }//GEN-LAST:event_insertCustomerClrBtnActionPerformed

    // INSERT ARTWORK SUBMIT BUTTON
    private void insertArtworkSbtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertArtworkSbtBtnActionPerformed
        String title = insertArtworkTitleTxt.getText();
        String genre = insertArtworkGenreTxt.getText();
        float price = Float.parseFloat(insertArtworkPriceTxt.getText());
        int crYear = Integer.parseInt(insertArtworkCreationYearTxt.getText());
        int inYear = Integer.parseInt(insertArtworkInsertionYearTxt.getText());
        
        int artistId =  Integer.parseInt(insertArtworkArtistIdCbx.getSelectedItem().toString());
        
        //check if combobox value is NONE or int.
        int orderId =  connectQueries.checkComboboxInt(insertArtworkOrderIdCbx);
        
        if(connectQueries.insertArtworkInsertFrame(title, orderId, artistId, genre,  price, crYear, inYear)){
            insertMsgLbl.setText("Artwork Record Inserted Successfully.");
        }else{
            insertMsgLbl.setText("Artwork Record Insertion Failed.");
        }
    }//GEN-LAST:event_insertArtworkSbtBtnActionPerformed

    // INSERT ARTWORK CLEAR BUTTON
    private void insertArtworkClrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertArtworkClrBtnActionPerformed
        insertArtworkTitleTxt.setText("");
        insertArtworkGenreTxt.setText("");
        insertArtworkPriceTxt.setText("");
        insertArtworkCreationYearTxt.setText("");
        insertArtworkInsertionYearTxt.setText("");
        insertMsgLbl.setText("");
        
    }//GEN-LAST:event_insertArtworkClrBtnActionPerformed

    // INSERT ORDER SUBMIT BUTTON
    private void insertOrderSbtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertOrderSbtBtnActionPerformed
        String title = insertOrderTitleCbx.getSelectedItem().toString();
        int custId = Integer.parseInt(insertOrderCustomerIdCbx.getSelectedItem().toString());
        int orderYear = Integer.parseInt(insertOrderOrderYearTxt.getText());
        
        if(connectQueries.insertOrderInsertFrame(title, custId, orderYear)) {
            insertMsgLbl.setText("Order Record Inserted Successfully.");
        } else {
            insertMsgLbl.setText("Order Record Insertion Failed.");
        }  
    }//GEN-LAST:event_insertOrderSbtBtnActionPerformed

    // INSERT ORDER CLEAR BUTTON
    private void insertOrderClrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertOrderClrBtnActionPerformed
        insertOrderOrderYearTxt.setText("");
        insertMsgLbl.setText("");
    }//GEN-LAST:event_insertOrderClrBtnActionPerformed

    //INSERT NAMEOFGROUP SUBMIT BUTTON
    private void insertGroupSbtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertGroupSbtBtnActionPerformed
        String nameOfGroup = insertGroupNameTxt.getText();
        
        if(connectQueries.insertNameOfGroupInsertFrame(nameOfGroup)){
            insertMsgLbl.setText("Group Record Inserted Successfully.");
        }else {
            insertMsgLbl.setText("Group Record Insertion Failed.");
        }
        
    }//GEN-LAST:event_insertGroupSbtBtnActionPerformed

    // INSERT CUSTOMER LIKES ARTIST SUBMIT BUTTON
    private void insertCustLikeArtistSbtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertCustLikeArtistSbtBtnActionPerformed
        int custId = Integer.parseInt(insertCustLikeArtistCustIdCbx.getSelectedItem().toString());
        int artistId = Integer.parseInt(insertCustLikeArtistArtistIdCbx.getSelectedItem().toString());
        
        if(connectQueries.insertCustLikesArtistInsertFrame(custId, artistId)){
            insertMsgLbl.setText("Customer Likes Artist Record Inserted Successfully.");
        } else {
            insertMsgLbl.setText("Customer Likes Artist Record Insertion Failed.");
        }
    }//GEN-LAST:event_insertCustLikeArtistSbtBtnActionPerformed

    // INSERT CUSTOMER LIKES ARTIST CLEAR BUTTON
    private void insertCustLikeArtistClrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertCustLikeArtistClrBtnActionPerformed
        insertMsgLbl.setText("");
    }//GEN-LAST:event_insertCustLikeArtistClrBtnActionPerformed

    // INSERT ARTWORK CLASSIFIES TO GROUP SUBMIT BUTTON
    private void insertArtworkClassGroupArtworkSbtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertArtworkClassGroupArtworkSbtBtnActionPerformed
        String title = insertArtworkClassGroupArtworkNameCbx.getSelectedItem().toString();
        String nameOfGroup = insertArtworkClassGroupGroupNameCbx.getSelectedItem().toString();
        
        if(connectQueries.insertArtworkClassGroupInsertFrame(title, nameOfGroup)){
            insertMsgLbl.setText("Artwork classifies to Group Record Inserted Successfully.");
        }else{
            insertMsgLbl.setText("Artwork classified to Group Record Insertion Failed.");
        }
    }//GEN-LAST:event_insertArtworkClassGroupArtworkSbtBtnActionPerformed

    //ΙNSERT GROUP CLEAR BUTTON
    private void insertGroupClrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertGroupClrBtnActionPerformed
        insertMsgLbl.setText("");
        insertGroupNameTxt.setText("");
    }//GEN-LAST:event_insertGroupClrBtnActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton disconnectInsertFrameBtn;
    private javax.swing.JButton insertArtistClrBtn;
    private javax.swing.JTextField insertArtistLocationTxt;
    private javax.swing.JTextField insertArtistNameTxt;
    private javax.swing.JTextField insertArtistPhoneTxt;
    private javax.swing.JButton insertArtistSbtBtn;
    private javax.swing.JTextField insertArtistStyleTxt;
    private javax.swing.JComboBox insertArtworkArtistIdCbx;
    private javax.swing.JButton insertArtworkClassGroupArtworkClrBtn;
    private javax.swing.JComboBox insertArtworkClassGroupArtworkNameCbx;
    private javax.swing.JButton insertArtworkClassGroupArtworkSbtBtn;
    private javax.swing.JComboBox insertArtworkClassGroupGroupNameCbx;
    private javax.swing.JButton insertArtworkClrBtn;
    private javax.swing.JTextField insertArtworkCreationYearTxt;
    private javax.swing.JTextField insertArtworkGenreTxt;
    private javax.swing.JTextField insertArtworkInsertionYearTxt;
    private javax.swing.JComboBox insertArtworkOrderIdCbx;
    private javax.swing.JTextField insertArtworkPriceTxt;
    private javax.swing.JButton insertArtworkSbtBtn;
    private javax.swing.JTextField insertArtworkTitleTxt;
    private javax.swing.JComboBox insertCustLikeArtistArtistIdCbx;
    private javax.swing.JButton insertCustLikeArtistClrBtn;
    private javax.swing.JComboBox insertCustLikeArtistCustIdCbx;
    private javax.swing.JButton insertCustLikeArtistSbtBtn;
    private javax.swing.JButton insertCustomerClrBtn;
    private javax.swing.JTextField insertCustomerNameTxt;
    private javax.swing.JTextField insertCustomerPhoneTxt;
    private javax.swing.JButton insertCustomerSbtBtn;
    private javax.swing.JButton insertGroupClrBtn;
    private javax.swing.JTextField insertGroupNameTxt;
    private javax.swing.JButton insertGroupSbtBtn;
    private javax.swing.JLabel insertMsgLbl;
    private javax.swing.JButton insertOrderClrBtn;
    private javax.swing.JComboBox insertOrderCustomerIdCbx;
    private javax.swing.JTextField insertOrderOrderYearTxt;
    private javax.swing.JButton insertOrderSbtBtn;
    private javax.swing.JComboBox insertOrderTitleCbx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton mainMenuInsertFrameBtn;
    // End of variables declaration//GEN-END:variables
}
