package galleryPkg;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Maria
 */
public class UpdateFrame extends javax.swing.JFrame {

    /**
     * Creates new form UpdateFrame
     */
    public UpdateFrame() {
        initComponents();
        connectQueries.FillArtistIdCbx(updateArtistCbx);
        connectQueries.FillCustomerIdCbx(updateCustomerCbx);
        connectQueries.FillArtworkTitleCbx(updateArtworkCbx);
        connectQueries.FillCustomerIdCbx(updateCustLikeArtistCbx);
        connectQueries.FillOrderIdCbx(updateOrderCbx);
        connectQueries.FillArtworkTitleCbx(updateArtworkClassGroupCbx);
        connectQueries.FillNameOfGroupCbx(updateGroupCbx);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mainMenuUpdateFrameBtn = new javax.swing.JButton();
        disconnectUpdateFrameBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        updateMsgLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        updateArtistNameTxt = new javax.swing.JTextField();
        updateArtistStyleTxt = new javax.swing.JTextField();
        updateArtistLocationTxt = new javax.swing.JTextField();
        updateArtistPhoneTxt = new javax.swing.JTextField();
        updateArtistSbtBtn = new javax.swing.JButton();
        updateArtistClrBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        updateArtistCbx = new javax.swing.JComboBox();
        updateArtistSlBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        updateCustomerClrBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        updateCustomerNameTxt = new javax.swing.JTextField();
        updateCustomerPhoneTxt = new javax.swing.JTextField();
        updateCustomerSbtBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        updateCustomerCbx = new javax.swing.JComboBox();
        updateCustomerSlBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        updateArtworkSbtBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        updateArtworkClrBtn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        updateArtworkInsertionYearTxt = new javax.swing.JTextField();
        updateArtworkGenreTxt = new javax.swing.JTextField();
        updateArtworkPriceTxt = new javax.swing.JTextField();
        updateArtworkCreationYearTxt = new javax.swing.JTextField();
        updateArtworkArtistIdTxt = new javax.swing.JTextField();
        updateArtworkTitleTxt = new javax.swing.JTextField();
        updateArtworkOrderIdTxt = new javax.swing.JTextField();
        updateArtworkSlBtn = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        updateArtworkCbx = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        updateOrderTitleTxt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        updateOrderOrderYearTxt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        updateOrderCustomerIdTxt = new javax.swing.JTextField();
        updateOrderSbtBtn = new javax.swing.JButton();
        updateOrderClrBtn = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        updateOrderSlBtn = new javax.swing.JButton();
        updateOrderCbx = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        updateGroupNameTxt = new javax.swing.JTextField();
        updateGroupSbtBtn = new javax.swing.JButton();
        updateGroupClrBtn = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        updateGroupCbx = new javax.swing.JComboBox();
        updateGroupSlBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        updateCustLikeArtistCustIdTxt = new javax.swing.JTextField();
        updateCustLikeArtistArtistIdTxt = new javax.swing.JTextField();
        updateCustLikeArtistSbtBtn = new javax.swing.JButton();
        updateCustLikeArtistClrBtn = new javax.swing.JButton();
        updateCustLikeArtistCbx = new javax.swing.JComboBox();
        updateCustLikeArtistSlBtn = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        updateArtworkClassGroupArtworkNameTxt = new javax.swing.JTextField();
        updateArtworkClassGroupGroupNameTxt = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        updateArtworkClassGroupArtworkSbtBtn = new javax.swing.JButton();
        updateArtworkClassGroupArtworkClrBtn = new javax.swing.JButton();
        updateArtworkClassGroupBtn = new javax.swing.JButton();
        updateArtworkClassGroupCbx = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Update Records");

        mainMenuUpdateFrameBtn.setText("MainMenu");
        mainMenuUpdateFrameBtn.setPreferredSize(new java.awt.Dimension(85, 23));
        mainMenuUpdateFrameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuUpdateFrameBtnActionPerformed(evt);
            }
        });

        disconnectUpdateFrameBtn.setText("Disconnect");
        disconnectUpdateFrameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectUpdateFrameBtnActionPerformed(evt);
            }
        });

        updateMsgLbl.setForeground(new java.awt.Color(204, 153, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Artist Record: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 102))); // NOI18N

        jLabel3.setText("Name: ");

        jLabel4.setText("Style: ");

        jLabel5.setText("Location (Country): ");

        jLabel6.setText("Phone Number:");

        updateArtistNameTxt.setEnabled(false);

        updateArtistStyleTxt.setEnabled(false);

        updateArtistLocationTxt.setEnabled(false);

        updateArtistPhoneTxt.setEnabled(false);

        updateArtistSbtBtn.setText("Update");
        updateArtistSbtBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        updateArtistSbtBtn.setMinimumSize(new java.awt.Dimension(100, 23));
        updateArtistSbtBtn.setPreferredSize(new java.awt.Dimension(100, 23));
        updateArtistSbtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateArtistSbtBtnActionPerformed(evt);
            }
        });

        updateArtistClrBtn.setText("Clear");
        updateArtistClrBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        updateArtistClrBtn.setMinimumSize(new java.awt.Dimension(100, 23));
        updateArtistClrBtn.setPreferredSize(new java.awt.Dimension(100, 23));
        updateArtistClrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateArtistClrBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Select Artist ID:");

        updateArtistSlBtn.setText("Select");
        updateArtistSlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateArtistSlBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(updateArtistCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateArtistSlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(updateArtistSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updateArtistPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateArtistClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateArtistNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateArtistStyleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateArtistLocationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateArtistCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateArtistSlBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(updateArtistNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(updateArtistStyleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(updateArtistLocationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(updateArtistPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateArtistSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateArtistClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Customer Record: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 102))); // NOI18N

        updateCustomerClrBtn.setText("Clear");
        updateCustomerClrBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        updateCustomerClrBtn.setMinimumSize(new java.awt.Dimension(100, 23));
        updateCustomerClrBtn.setPreferredSize(new java.awt.Dimension(100, 23));
        updateCustomerClrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerClrBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Name: ");

        jLabel9.setText("Phone Number: ");

        updateCustomerSbtBtn.setText("Update");
        updateCustomerSbtBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        updateCustomerSbtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerSbtBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Select Customer ID:");

        updateCustomerSlBtn.setText("Select");
        updateCustomerSlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerSlBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(updateCustomerSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateCustomerClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(updateCustomerCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(updateCustomerSlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updateCustomerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateCustomerPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateCustomerCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateCustomerSlBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(updateCustomerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(updateCustomerPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateCustomerSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateCustomerClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Artwork Record:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 102))); // NOI18N

        jLabel12.setText("Title: ");

        jLabel13.setText("Genre: ");

        jLabel14.setText("Price: ");

        jLabel15.setText("Creation Year: ");

        jLabel16.setText("Insertion Year: ");

        updateArtworkSbtBtn.setText("Update");
        updateArtworkSbtBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        updateArtworkSbtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateArtworkSbtBtnActionPerformed(evt);
            }
        });

        jLabel17.setText("Artist ID: ");

        updateArtworkClrBtn.setText("Clear");
        updateArtworkClrBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        updateArtworkClrBtn.setMinimumSize(new java.awt.Dimension(100, 23));
        updateArtworkClrBtn.setPreferredSize(new java.awt.Dimension(100, 23));
        updateArtworkClrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateArtworkClrBtnActionPerformed(evt);
            }
        });

        jLabel18.setText("Order ID: ");

        updateArtworkInsertionYearTxt.setEnabled(false);

        updateArtworkGenreTxt.setEnabled(false);

        updateArtworkPriceTxt.setEnabled(false);

        updateArtworkCreationYearTxt.setEnabled(false);

        updateArtworkArtistIdTxt.setEnabled(false);

        updateArtworkTitleTxt.setEnabled(false);

        updateArtworkOrderIdTxt.setEnabled(false);

        updateArtworkSlBtn.setText("Select");
        updateArtworkSlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateArtworkSlBtnActionPerformed(evt);
            }
        });

        jLabel30.setText("Select Artwork Title:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(updateArtworkCreationYearTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(updateArtworkInsertionYearTxt))
                                    .addComponent(updateArtworkGenreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateArtworkPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateArtworkTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(updateArtworkSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateArtworkClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel30)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(updateArtworkCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateArtworkSlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(updateArtworkOrderIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(updateArtworkArtistIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateArtworkCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateArtworkSlBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(updateArtworkTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(updateArtworkOrderIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(updateArtworkArtistIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(updateArtworkGenreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(updateArtworkPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(updateArtworkCreationYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(updateArtworkInsertionYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateArtworkSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateArtworkClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Order Record:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 102))); // NOI18N

        jLabel21.setText("Title ordered artwork: ");

        jLabel22.setText("Order Year: ");

        jLabel23.setText("Customer ID: ");

        updateOrderSbtBtn.setText("Update");
        updateOrderSbtBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        updateOrderSbtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateOrderSbtBtnActionPerformed(evt);
            }
        });

        updateOrderClrBtn.setText("Clear");
        updateOrderClrBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        updateOrderClrBtn.setMinimumSize(new java.awt.Dimension(100, 23));
        updateOrderClrBtn.setPreferredSize(new java.awt.Dimension(100, 23));
        updateOrderClrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateOrderClrBtnActionPerformed(evt);
            }
        });

        jLabel31.setText("Select Order ID:");

        updateOrderSlBtn.setText("Select");
        updateOrderSlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateOrderSlBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(updateOrderSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateOrderClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(updateOrderCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateOrderSlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updateOrderTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateOrderOrderYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateOrderCustomerIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel31))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateOrderCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateOrderSlBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(updateOrderTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(updateOrderCustomerIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(updateOrderOrderYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateOrderClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateOrderSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Group Record:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 102))); // NOI18N

        jLabel20.setText("Name of Group: ");

        updateGroupSbtBtn.setText("Update");
        updateGroupSbtBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        updateGroupSbtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateGroupSbtBtnActionPerformed(evt);
            }
        });

        updateGroupClrBtn.setText("Clear");
        updateGroupClrBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        updateGroupClrBtn.setMinimumSize(new java.awt.Dimension(100, 23));
        updateGroupClrBtn.setPreferredSize(new java.awt.Dimension(100, 23));
        updateGroupClrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateGroupClrBtnActionPerformed(evt);
            }
        });

        jLabel32.setText("Select Group Name:");

        updateGroupSlBtn.setText("Select");
        updateGroupSlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateGroupSlBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(updateGroupCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateGroupSlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateGroupSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updateGroupNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateGroupClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel32))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateGroupCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateGroupSlBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(updateGroupNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateGroupSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateGroupClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Customer Likes Artist:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 102))); // NOI18N

        jLabel25.setText("Customer ID: ");

        jLabel26.setText("Artist ID: ");

        updateCustLikeArtistSbtBtn.setText("Update");
        updateCustLikeArtistSbtBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        updateCustLikeArtistSbtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustLikeArtistSbtBtnActionPerformed(evt);
            }
        });

        updateCustLikeArtistClrBtn.setText("Clear");
        updateCustLikeArtistClrBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        updateCustLikeArtistClrBtn.setMinimumSize(new java.awt.Dimension(100, 23));
        updateCustLikeArtistClrBtn.setPreferredSize(new java.awt.Dimension(100, 23));
        updateCustLikeArtistClrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustLikeArtistClrBtnActionPerformed(evt);
            }
        });

        updateCustLikeArtistSlBtn.setText("Select");
        updateCustLikeArtistSlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustLikeArtistSlBtnActionPerformed(evt);
            }
        });

        jLabel33.setText("Select Customer ID:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(updateCustLikeArtistCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateCustLikeArtistSlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(updateCustLikeArtistSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(updateCustLikeArtistClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel33))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updateCustLikeArtistCustIdTxt)
                            .addComponent(updateCustLikeArtistArtistIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateCustLikeArtistCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateCustLikeArtistSlBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(updateCustLikeArtistCustIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(updateCustLikeArtistArtistIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateCustLikeArtistSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateCustLikeArtistClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Artwork Classifies to Group:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 102))); // NOI18N

        jLabel28.setText("Artwork Title: ");

        jLabel29.setText("Name of Group: ");

        updateArtworkClassGroupArtworkSbtBtn.setText("Update");
        updateArtworkClassGroupArtworkSbtBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        updateArtworkClassGroupArtworkSbtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateArtworkClassGroupArtworkSbtBtnActionPerformed(evt);
            }
        });

        updateArtworkClassGroupArtworkClrBtn.setText("Clear");
        updateArtworkClassGroupArtworkClrBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        updateArtworkClassGroupArtworkClrBtn.setMinimumSize(new java.awt.Dimension(100, 23));
        updateArtworkClassGroupArtworkClrBtn.setPreferredSize(new java.awt.Dimension(100, 23));
        updateArtworkClassGroupArtworkClrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateArtworkClassGroupArtworkClrBtnActionPerformed(evt);
            }
        });

        updateArtworkClassGroupBtn.setText("Select");
        updateArtworkClassGroupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateArtworkClassGroupBtnActionPerformed(evt);
            }
        });

        jLabel34.setText("Select Artwork Title:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(updateArtworkClassGroupArtworkSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(updateArtworkClassGroupArtworkNameTxt)
                        .addComponent(updateArtworkClassGroupGroupNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(updateArtworkClassGroupArtworkClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(updateArtworkClassGroupCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateArtworkClassGroupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel34))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateArtworkClassGroupCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateArtworkClassGroupBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(updateArtworkClassGroupArtworkNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(updateArtworkClassGroupGroupNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateArtworkClassGroupArtworkClrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateArtworkClassGroupArtworkSbtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(updateMsgLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mainMenuUpdateFrameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(disconnectUpdateFrameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mainMenuUpdateFrameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(disconnectUpdateFrameBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateMsgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void disconnectUpdateFrameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectUpdateFrameBtnActionPerformed
        LoginFrame loginFrame = new LoginFrame();
            loginFrame.setVisible(true);
            UpdateFrame.this.setVisible(false);
            connectQueries.disConnectDb();
            UpdateFrame.this.dispose();
    }//GEN-LAST:event_disconnectUpdateFrameBtnActionPerformed

    private void mainMenuUpdateFrameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuUpdateFrameBtnActionPerformed
        MainFrame mainFrame = new MainFrame();
        mainFrame.setVisible(true);
        UpdateFrame.this.setVisible(false);
        UpdateFrame.this.dispose();
    }//GEN-LAST:event_mainMenuUpdateFrameBtnActionPerformed

    //UPDATE ARTIST SELECT BUTTON
    private void updateArtistSlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateArtistSlBtnActionPerformed
        String selectionId = updateArtistCbx.getSelectedItem().toString();
        connectQueries.selectionFillArtist(selectionId, updateArtistStyleTxt, updateArtistNameTxt, updateArtistLocationTxt, updateArtistPhoneTxt);
        
        //Enable TextFields
        updateArtistStyleTxt.setEnabled(true);
        updateArtistNameTxt.setEnabled(true);
        updateArtistLocationTxt.setEnabled(true);
        updateArtistPhoneTxt.setEnabled(true);
    }//GEN-LAST:event_updateArtistSlBtnActionPerformed

    //UPDATE ARTIST SUBMIT BUTTON
    private void updateArtistSbtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateArtistSbtBtnActionPerformed
        String artistId = updateArtistCbx.getSelectedItem().toString();
        String artistStyle = updateArtistStyleTxt.getText();
        String artistName = updateArtistNameTxt.getText();
        String artistLoc = updateArtistLocationTxt.getText();
        String artistPhone = updateArtistPhoneTxt.getText();
        
        if(connectQueries.updateArtist(artistId, artistStyle, artistName, artistLoc, artistPhone)){
            updateMsgLbl.setText("Artist Record Updated.");
            //Disable TextFields and clear.
            updateArtistStyleTxt.setEnabled(false);
            updateArtistNameTxt.setEnabled(false);
            updateArtistLocationTxt.setEnabled(false);
            updateArtistPhoneTxt.setEnabled(false);
            
            updateArtistStyleTxt.setText("");
            updateArtistNameTxt.setText("");
            updateArtistLocationTxt.setText("");
            updateArtistPhoneTxt.setText("");
            
            
        }else{
            updateMsgLbl.setText("Artist Record Operation Failed.");
            //Disable TextFields and clear.
            updateArtistStyleTxt.setEnabled(false);
            updateArtistNameTxt.setEnabled(false);
            updateArtistLocationTxt.setEnabled(false);
            updateArtistPhoneTxt.setEnabled(false);
            
            updateArtistStyleTxt.setText("");
            updateArtistNameTxt.setText("");
            updateArtistLocationTxt.setText("");
            updateArtistPhoneTxt.setText("");
        }
        
        
        
    }//GEN-LAST:event_updateArtistSbtBtnActionPerformed

    // UPDATE ARTIST CLEAR BUTTON
    private void updateArtistClrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateArtistClrBtnActionPerformed
        //Disable TextFields and clear.
            updateArtistStyleTxt.setEnabled(false);
            updateArtistNameTxt.setEnabled(false);
            updateArtistLocationTxt.setEnabled(false);
            updateArtistPhoneTxt.setEnabled(false);
            
            updateArtistStyleTxt.setText("");
            updateArtistNameTxt.setText("");
            updateArtistLocationTxt.setText("");
            updateArtistPhoneTxt.setText("");
    }//GEN-LAST:event_updateArtistClrBtnActionPerformed

    //UPDATE ARTWORK SELECT BUTTON
    private void updateArtworkSlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateArtworkSlBtnActionPerformed
        String selectionTitle = updateArtworkCbx.getSelectedItem().toString();
        
        connectQueries.selectionFillArtwork(selectionTitle, updateArtworkTitleTxt, updateArtworkOrderIdTxt, updateArtworkArtistIdTxt, updateArtworkGenreTxt, updateArtworkPriceTxt, updateArtworkCreationYearTxt, updateArtworkInsertionYearTxt);
                
        //Enable TextFields
        updateArtworkTitleTxt.setEnabled(true);
        updateArtworkOrderIdTxt.setEnabled(true);
        updateArtworkArtistIdTxt.setEnabled(true);
        updateArtworkGenreTxt.setEnabled(true);
        updateArtworkPriceTxt.setEnabled(true);
        updateArtworkCreationYearTxt.setEnabled(true);
        updateArtworkInsertionYearTxt.setEnabled(true);
    }//GEN-LAST:event_updateArtworkSlBtnActionPerformed

    //UPDATE ARTWORK SUBMIT BUTTON
    private void updateArtworkSbtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateArtworkSbtBtnActionPerformed
        String title = updateArtworkTitleTxt.getText();
        String orderId = updateArtworkOrderIdTxt.getText();
        String artistId = updateArtworkArtistIdTxt.getText();
        String genre = updateArtworkGenreTxt.getText();
        String price = updateArtworkPriceTxt.getText();
        String crYear = updateArtworkCreationYearTxt.getText();
        String inYear = updateArtworkInsertionYearTxt.getText();
        
        if(connectQueries.updateArtwork(title, orderId, artistId, genre, price, crYear, inYear)){
            updateMsgLbl.setText("Artwork Record Updated.");
            
            //Disable TextFields and Clear
            updateArtworkTitleTxt.setEnabled(false);
            updateArtworkOrderIdTxt.setEnabled(false);
            updateArtworkArtistIdTxt.setEnabled(false);
            updateArtworkGenreTxt.setEnabled(false);
            updateArtworkPriceTxt.setEnabled(false);
            updateArtworkCreationYearTxt.setEnabled(false);
            updateArtworkInsertionYearTxt.setEnabled(false);
            
            updateArtworkTitleTxt.setText("");
            updateArtworkOrderIdTxt.setText("");
            updateArtworkArtistIdTxt.setText("");
            updateArtworkGenreTxt.setText("");
            updateArtworkPriceTxt.setText("");
            updateArtworkCreationYearTxt.setText("");
            updateArtworkInsertionYearTxt.setText("");
            
        } else{
            updateMsgLbl.setText("Artwork Record Operation Failed.");
            
            //Disable TextFields and Clear
            updateArtworkTitleTxt.setEnabled(false);
            updateArtworkOrderIdTxt.setEnabled(false);
            updateArtworkArtistIdTxt.setEnabled(false);
            updateArtworkGenreTxt.setEnabled(false);
            updateArtworkPriceTxt.setEnabled(false);
            updateArtworkCreationYearTxt.setEnabled(false);
            updateArtworkInsertionYearTxt.setEnabled(false);
            
            updateArtworkTitleTxt.setText("");
            updateArtworkOrderIdTxt.setText("");
            updateArtworkArtistIdTxt.setText("");
            updateArtworkGenreTxt.setText("");
            updateArtworkPriceTxt.setText("");
            updateArtworkCreationYearTxt.setText("");
            updateArtworkInsertionYearTxt.setText("");
        }
        
    }//GEN-LAST:event_updateArtworkSbtBtnActionPerformed

    //UPDATE ARTWORK CLEAR BUTTON
    private void updateArtworkClrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateArtworkClrBtnActionPerformed
            updateMsgLbl.setText("");

            //Disable TextFields and Clear
            updateArtworkTitleTxt.setEnabled(false);
            updateArtworkOrderIdTxt.setEnabled(false);
            updateArtworkArtistIdTxt.setEnabled(false);
            updateArtworkGenreTxt.setEnabled(false);
            updateArtworkPriceTxt.setEnabled(false);
            updateArtworkCreationYearTxt.setEnabled(false);
            updateArtworkInsertionYearTxt.setEnabled(false);
            
            updateArtworkTitleTxt.setText("");
            updateArtworkOrderIdTxt.setText("");
            updateArtworkArtistIdTxt.setText("");
            updateArtworkGenreTxt.setText("");
            updateArtworkPriceTxt.setText("");
            updateArtworkCreationYearTxt.setText("");
            updateArtworkInsertionYearTxt.setText("");
    }//GEN-LAST:event_updateArtworkClrBtnActionPerformed

    //UPDATE CUSTOMER SELECT BUTTON
    private void updateCustomerSlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerSlBtnActionPerformed
        String custId = updateCustomerCbx.getSelectedItem().toString();
        connectQueries.selectionFillCustomer(custId, updateCustomerNameTxt, updateCustomerPhoneTxt);
        
        updateCustomerNameTxt.setEnabled(true);
        updateCustomerPhoneTxt.setEnabled(true);
        

    }//GEN-LAST:event_updateCustomerSlBtnActionPerformed

    //UPDATE CUSTOMER SUBMIT BUTTON
    private void updateCustomerSbtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerSbtBtnActionPerformed
        String custId = updateCustomerCbx.getSelectedItem().toString();
        String custName = updateCustomerNameTxt.getText();
        String phone = updateCustomerPhoneTxt.getText();
        
        if(connectQueries.updateCustomer(custId, custName , phone)){
            updateMsgLbl.setText("Customer Record Updated.");
            
            //Disable Textfields and Clear
            updateCustomerNameTxt.setEnabled(false);
            updateCustomerPhoneTxt.setEnabled(false);
            
            updateCustomerNameTxt.setText("");
            updateCustomerPhoneTxt.setText("");
        }else{
            updateMsgLbl.setText("Customer Record Operation Failed.");
            
            //Disable Textfields and Clear
            updateCustomerNameTxt.setEnabled(false);
            updateCustomerPhoneTxt.setEnabled(false);
            
            updateCustomerNameTxt.setText("");
            updateCustomerPhoneTxt.setText("");
        }
    }//GEN-LAST:event_updateCustomerSbtBtnActionPerformed

    //UPDATE CUSTOMER CLEAR BUTTON
    private void updateCustomerClrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerClrBtnActionPerformed
            updateMsgLbl.setText("");
            //Disable Textfields and Clear
            updateCustomerNameTxt.setEnabled(false);
            updateCustomerPhoneTxt.setEnabled(false);
            
            updateCustomerNameTxt.setText("");
            updateCustomerPhoneTxt.setText("");
    }//GEN-LAST:event_updateCustomerClrBtnActionPerformed

    //UPDATE ORDER SELECT BUTTON
    private void updateOrderSlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateOrderSlBtnActionPerformed
        String orderId = updateOrderCbx.getSelectedItem().toString();
        
        connectQueries.selectionFillOrder(orderId, updateOrderTitleTxt, updateOrderCustomerIdTxt, updateOrderOrderYearTxt);
        
        //Enable TextFields
        updateOrderTitleTxt.setEnabled(true);
        updateOrderCustomerIdTxt.setEnabled(true);
        updateOrderOrderYearTxt.setEnabled(true);
    }//GEN-LAST:event_updateOrderSlBtnActionPerformed

    //UPDATE ORDER SUBMIT BUTTON
    private void updateOrderSbtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateOrderSbtBtnActionPerformed
        String orderId = updateOrderCbx.getSelectedItem().toString();
        String title = updateOrderTitleTxt.getText();
        String custId = updateOrderCustomerIdTxt.getText();
        String orderYear = updateOrderOrderYearTxt.getText();
        
        if(connectQueries.updateOrder(orderId, title, custId, orderYear)){
            updateMsgLbl.setText("Order Record Updated.");
            
            //Disable TextFields and Clear
            updateOrderTitleTxt.setEnabled(false);
            updateOrderCustomerIdTxt.setEnabled(false);
            updateOrderOrderYearTxt.setEnabled(false);
            
            updateOrderTitleTxt.setText("");
            updateOrderCustomerIdTxt.setText("");
            updateOrderOrderYearTxt.setText("");
        }else{
            updateMsgLbl.setText("Order Record Operation Failed.");
            //Disable TextFields and Clear
            updateOrderTitleTxt.setEnabled(false);
            updateOrderCustomerIdTxt.setEnabled(false);
            updateOrderOrderYearTxt.setEnabled(false);
            
            updateOrderTitleTxt.setText("");
            updateOrderCustomerIdTxt.setText("");
            updateOrderOrderYearTxt.setText("");
        }
        
    }//GEN-LAST:event_updateOrderSbtBtnActionPerformed

    //UPDATE ORDER CLEAR BUTTON
    private void updateOrderClrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateOrderClrBtnActionPerformed
            updateMsgLbl.setText("");

            //Disable TextFields and Clear
            updateOrderTitleTxt.setEnabled(false);
            updateOrderCustomerIdTxt.setEnabled(false);
            updateOrderOrderYearTxt.setEnabled(false);
            
            updateOrderTitleTxt.setText("");
            updateOrderCustomerIdTxt.setText("");
            updateOrderOrderYearTxt.setText("");
    }//GEN-LAST:event_updateOrderClrBtnActionPerformed

    // UPDATE CUSTLIKEARTIST SELECT BUTTON
    private void updateCustLikeArtistSlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustLikeArtistSlBtnActionPerformed
        String custId = updateCustLikeArtistCbx.getSelectedItem().toString();
        
        connectQueries.selectionFillCustomerLikeArtist(custId, updateCustLikeArtistCustIdTxt, updateCustLikeArtistArtistIdTxt);
        
        //Enable TextFields
        updateCustLikeArtistCustIdTxt.setEnabled(true);
        updateCustLikeArtistCustIdTxt.setEnabled(true);
    }//GEN-LAST:event_updateCustLikeArtistSlBtnActionPerformed

    // UPDATE CUSTLIKEARTIST SUBMIT BUTTON
    private void updateCustLikeArtistSbtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustLikeArtistSbtBtnActionPerformed
        String custId = updateCustLikeArtistCbx.getSelectedItem().toString();
        String custIdTxt= updateCustLikeArtistCustIdTxt.getText();
        String artistId = updateCustLikeArtistArtistIdTxt.getText();
        
        if(connectQueries.updateCustomerLikesArtist(custId, custIdTxt, artistId)){
            updateMsgLbl.setText("Customer Likes Artist Record Updated.");
            
            //Disable TextFields and Clear
            updateCustLikeArtistCustIdTxt.setEnabled(false);
            updateCustLikeArtistArtistIdTxt.setEnabled(false);
            updateCustLikeArtistCustIdTxt.setText("");
            updateCustLikeArtistArtistIdTxt.setText("");
            
        }else{
            updateMsgLbl.setText("Customer Likes Artist Operation Failed.");
            //Disable TextFields and Clear
            updateCustLikeArtistCustIdTxt.setEnabled(false);
            updateCustLikeArtistArtistIdTxt.setEnabled(false);
            updateCustLikeArtistCustIdTxt.setText("");
            updateCustLikeArtistArtistIdTxt.setText("");
        }
    }//GEN-LAST:event_updateCustLikeArtistSbtBtnActionPerformed

    //UPDATE CUSTLIKEARTIST CLEAR BUTTON
    private void updateCustLikeArtistClrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustLikeArtistClrBtnActionPerformed
            updateMsgLbl.setText("");
            //Disable TextFields and Clear
            updateCustLikeArtistCustIdTxt.setEnabled(false);
            updateCustLikeArtistArtistIdTxt.setEnabled(false);
            updateCustLikeArtistCustIdTxt.setText("");
            updateCustLikeArtistArtistIdTxt.setText("");
    }//GEN-LAST:event_updateCustLikeArtistClrBtnActionPerformed

    //UPDATE ARTWORKCLASSGROUP SELECT BUTTON
    private void updateArtworkClassGroupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateArtworkClassGroupBtnActionPerformed
        String artTitle = updateArtworkClassGroupCbx.getSelectedItem().toString();
        
        connectQueries.selectionFillArtworkClassGroup(artTitle, updateArtworkClassGroupArtworkNameTxt, updateArtworkClassGroupGroupNameTxt);
        
        updateArtworkClassGroupArtworkNameTxt.setEnabled(true);
        updateArtworkClassGroupGroupNameTxt.setEnabled(true);
    }//GEN-LAST:event_updateArtworkClassGroupBtnActionPerformed

    //UPDATE ARTWORKCLASSGROUP SUBMIT BUTTON
    private void updateArtworkClassGroupArtworkSbtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateArtworkClassGroupArtworkSbtBtnActionPerformed
        String artTitle = updateArtworkClassGroupCbx.getSelectedItem().toString();
        String title = updateArtworkClassGroupArtworkNameTxt.getText();
        String group = updateArtworkClassGroupGroupNameTxt.getText();
        
        if(connectQueries.updateArtworkClassGroup(artTitle, title, group)){
            updateMsgLbl.setText("Artwork Class Group Record Updated.");
            
            //Disable textfield and clear
            updateArtworkClassGroupArtworkNameTxt.setEnabled(false);
            updateArtworkClassGroupGroupNameTxt.setEnabled(false);
            updateArtworkClassGroupArtworkNameTxt.setText("");
            updateArtworkClassGroupGroupNameTxt.setText("");
        }else{
            updateMsgLbl.setText("Artwork Class Group Operation Failed.");
            
            //Disable textfield and clear
            updateArtworkClassGroupArtworkNameTxt.setEnabled(false);
            updateArtworkClassGroupGroupNameTxt.setEnabled(false);
            updateArtworkClassGroupArtworkNameTxt.setText("");
            updateArtworkClassGroupGroupNameTxt.setText("");
        }
        
        
    }//GEN-LAST:event_updateArtworkClassGroupArtworkSbtBtnActionPerformed

    //UPDATE ARTWORKCLASSGROUP CLEAR BUTTON
    private void updateArtworkClassGroupArtworkClrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateArtworkClassGroupArtworkClrBtnActionPerformed
            updateMsgLbl.setText("");
            
            //Disable textfield and clear
            updateArtworkClassGroupArtworkNameTxt.setEnabled(false);
            updateArtworkClassGroupGroupNameTxt.setEnabled(false);
            updateArtworkClassGroupArtworkNameTxt.setText("");
            updateArtworkClassGroupGroupNameTxt.setText("");
    }//GEN-LAST:event_updateArtworkClassGroupArtworkClrBtnActionPerformed

    ////UPDATE GROUP SELECT BUTTON
    private void updateGroupSlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateGroupSlBtnActionPerformed
        String groupName = updateGroupCbx.getSelectedItem().toString();
        
        connectQueries.selectionFillNameOfGroup(groupName, updateGroupNameTxt);
        updateGroupNameTxt.setEnabled(true);
    }//GEN-LAST:event_updateGroupSlBtnActionPerformed

    ////UPDATE GROUP SUBMIT BUTTON
    private void updateGroupSbtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateGroupSbtBtnActionPerformed
        String groupName = updateGroupCbx.getSelectedItem().toString();
        String groupNameTxt = updateGroupNameTxt.getText();
        
        if(connectQueries.updateNameOfGroup(groupName, groupNameTxt)){
            updateMsgLbl.setText("Group Record Updated.");
            
            //Disable textfield and clear
            updateGroupNameTxt.setEnabled(false);
            updateGroupNameTxt.setText("");
        }else{
            updateMsgLbl.setText("Group Record Operation Failed.");
            
            //Disable textfield and clear
            updateGroupNameTxt.setEnabled(false);
            updateGroupNameTxt.setText("");
        }
    }//GEN-LAST:event_updateGroupSbtBtnActionPerformed

    ////UPDATE GROUP CLEAR BUTTON
    private void updateGroupClrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateGroupClrBtnActionPerformed
        updateMsgLbl.setText("");
            
            //Disable textfield and clear
            updateGroupNameTxt.setEnabled(false);
            updateGroupNameTxt.setText("");
    }//GEN-LAST:event_updateGroupClrBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton disconnectUpdateFrameBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton mainMenuUpdateFrameBtn;
    private javax.swing.JComboBox updateArtistCbx;
    private javax.swing.JButton updateArtistClrBtn;
    private javax.swing.JTextField updateArtistLocationTxt;
    private javax.swing.JTextField updateArtistNameTxt;
    private javax.swing.JTextField updateArtistPhoneTxt;
    private javax.swing.JButton updateArtistSbtBtn;
    private javax.swing.JButton updateArtistSlBtn;
    private javax.swing.JTextField updateArtistStyleTxt;
    private javax.swing.JTextField updateArtworkArtistIdTxt;
    private javax.swing.JComboBox updateArtworkCbx;
    private javax.swing.JButton updateArtworkClassGroupArtworkClrBtn;
    private javax.swing.JTextField updateArtworkClassGroupArtworkNameTxt;
    private javax.swing.JButton updateArtworkClassGroupArtworkSbtBtn;
    private javax.swing.JButton updateArtworkClassGroupBtn;
    private javax.swing.JComboBox updateArtworkClassGroupCbx;
    private javax.swing.JTextField updateArtworkClassGroupGroupNameTxt;
    private javax.swing.JButton updateArtworkClrBtn;
    private javax.swing.JTextField updateArtworkCreationYearTxt;
    private javax.swing.JTextField updateArtworkGenreTxt;
    private javax.swing.JTextField updateArtworkInsertionYearTxt;
    private javax.swing.JTextField updateArtworkOrderIdTxt;
    private javax.swing.JTextField updateArtworkPriceTxt;
    private javax.swing.JButton updateArtworkSbtBtn;
    private javax.swing.JButton updateArtworkSlBtn;
    private javax.swing.JTextField updateArtworkTitleTxt;
    private javax.swing.JTextField updateCustLikeArtistArtistIdTxt;
    private javax.swing.JComboBox updateCustLikeArtistCbx;
    private javax.swing.JButton updateCustLikeArtistClrBtn;
    private javax.swing.JTextField updateCustLikeArtistCustIdTxt;
    private javax.swing.JButton updateCustLikeArtistSbtBtn;
    private javax.swing.JButton updateCustLikeArtistSlBtn;
    private javax.swing.JComboBox updateCustomerCbx;
    private javax.swing.JButton updateCustomerClrBtn;
    private javax.swing.JTextField updateCustomerNameTxt;
    private javax.swing.JTextField updateCustomerPhoneTxt;
    private javax.swing.JButton updateCustomerSbtBtn;
    private javax.swing.JButton updateCustomerSlBtn;
    private javax.swing.JComboBox updateGroupCbx;
    private javax.swing.JButton updateGroupClrBtn;
    private javax.swing.JTextField updateGroupNameTxt;
    private javax.swing.JButton updateGroupSbtBtn;
    private javax.swing.JButton updateGroupSlBtn;
    private javax.swing.JLabel updateMsgLbl;
    private javax.swing.JComboBox updateOrderCbx;
    private javax.swing.JButton updateOrderClrBtn;
    private javax.swing.JTextField updateOrderCustomerIdTxt;
    private javax.swing.JTextField updateOrderOrderYearTxt;
    private javax.swing.JButton updateOrderSbtBtn;
    private javax.swing.JButton updateOrderSlBtn;
    private javax.swing.JTextField updateOrderTitleTxt;
    // End of variables declaration//GEN-END:variables
}
